/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interesys.sistema;

/**
 *
 * @author PROGRAMADOR-02
 */
public class ImprimirVew extends javax.swing.JFrame {

	/**
	 * Creates new form ImprimirVew
	 */
	public ImprimirVew() {
		this.initComponents();
		this.inicializar();
	}

	private void inicializar() {
		ImprimirVewCtrl imprimirVewCtrl = ImprimirVewCtrl.getInstancia();
		imprimirVewCtrl.setImprimirVew(this);
		imprimirVewCtrl.inicializar();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Impressão = new javax.swing.ButtonGroup();
		Agrupamento = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		btnNumeroItem = new javax.swing.JRadioButton();
		btnDescricao = new javax.swing.JRadioButton();
		jLabel1 = new javax.swing.JLabel();
		btnCodigoProduto = new javax.swing.JRadioButton();
		btnGrupo_Descricao = new javax.swing.JRadioButton();
		btnGrupo_Codigo = new javax.swing.JRadioButton();
		btnGrupo_Subgrupo_Descricao = new javax.swing.JRadioButton();
		btnGrupo_Subgrupo_Codigo = new javax.swing.JRadioButton();
		btnSecao = new javax.swing.JRadioButton();
		btnGrupo_Subgrupo_agru = new javax.swing.JRadioButton();
		jLabel2 = new javax.swing.JLabel();
		btnGrupo_agru = new javax.swing.JRadioButton();
		btnSemAgrupar_agru = new javax.swing.JRadioButton();
		btnAmbiente_agru = new javax.swing.JRadioButton();
		btnImpressao_aut = new javax.swing.JRadioButton();
		linha = new javax.swing.JLabel();
		btnImprimir = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		btnSalvar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(java.awt.SystemColor.activeCaption);
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

		Impressão.add(btnNumeroItem);
		btnNumeroItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnNumeroItem.setText("Número de Item");

		Impressão.add(btnDescricao);
		btnDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnDescricao.setText("Descrição");

		jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabel1.setText("Ordem de Impressão");

		Impressão.add(btnCodigoProduto);
		btnCodigoProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnCodigoProduto.setText("Código do Produto");

		Impressão.add(btnGrupo_Descricao);
		btnGrupo_Descricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnGrupo_Descricao.setText("Grupo do Produto + Descrição");

		Impressão.add(btnGrupo_Codigo);
		btnGrupo_Codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnGrupo_Codigo.setText("Grupo do Prodiuto + Código do Produto");

		Impressão.add(btnGrupo_Subgrupo_Descricao);
		btnGrupo_Subgrupo_Descricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnGrupo_Subgrupo_Descricao.setText("Grupo do Produto + Subgrupo do Produto + Descrição");

		Impressão.add(btnGrupo_Subgrupo_Codigo);
		btnGrupo_Subgrupo_Codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnGrupo_Subgrupo_Codigo.setText("Grupo do Produto + Subgrupo do Produto +Código");

		Impressão.add(btnSecao);
		btnSecao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnSecao.setText("Seção");

		Agrupamento.add(btnGrupo_Subgrupo_agru);
		btnGrupo_Subgrupo_agru.setText("Grupo + Subgrupo");

		jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		jLabel2.setText("Agrupamento");

		Agrupamento.add(btnGrupo_agru);
		btnGrupo_agru.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnGrupo_agru.setText("Grupo");

		Agrupamento.add(btnSemAgrupar_agru);
		btnSemAgrupar_agru.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnSemAgrupar_agru.setText("Sem Agrupar");

		Agrupamento.add(btnAmbiente_agru);
		btnAmbiente_agru.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnAmbiente_agru.setText("Ambiente");

		btnImpressao_aut.setText("Impressão Automatica");

		linha.setText("______________________________________________________________________________________________");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
						.createSequentialGroup().addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnNumeroItem)
												.addComponent(
														btnDescricao, javax.swing.GroupLayout.PREFERRED_SIZE,
														103, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnCodigoProduto)
												.addComponent(btnGrupo_Descricao))
										.addGap(34, 34, 34)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(btnGrupo_Subgrupo_Descricao,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(btnGrupo_Codigo).addComponent(btnSecao).addComponent(
														btnGrupo_Subgrupo_Codigo, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(194, 194, 194)
										.addComponent(jLabel1))
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(219, 219, 219)
										.addComponent(jLabel2))
								.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnGrupo_agru).addComponent(
														btnGrupo_Subgrupo_agru, javax.swing.GroupLayout.PREFERRED_SIZE,
														127, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(99, 99, 99)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnAmbiente_agru).addComponent(btnSemAgrupar_agru)))
								.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
										.addComponent(btnImpressao_aut)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addComponent(linha,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel1).addGap(8, 8, 8)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnNumeroItem).addComponent(btnGrupo_Subgrupo_Descricao))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDescricao).addComponent(btnGrupo_Subgrupo_Codigo))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnCodigoProduto).addComponent(btnGrupo_Codigo))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnGrupo_Descricao).addComponent(btnSecao))
						.addGap(18, 18, 18).addComponent(jLabel2).addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnGrupo_Subgrupo_agru).addComponent(btnAmbiente_agru))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnGrupo_agru).addComponent(btnSemAgrupar_agru))
						.addGap(18, 18, 18).addComponent(linha)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(btnImpressao_aut)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnImprimir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnImprimir.setText("Imprimir");

		btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnCancelar.setText("Cencelar");

		btnSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
		btnSalvar.setText("Salvar");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(11, 11, 11)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ImprimirVew.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ImprimirVew.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ImprimirVew.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ImprimirVew.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ImprimirVew().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup Agrupamento;
	private javax.swing.ButtonGroup Impressão;
	private javax.swing.JRadioButton btnAmbiente_agru;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JRadioButton btnCodigoProduto;
	private javax.swing.JRadioButton btnDescricao;
	private javax.swing.JRadioButton btnGrupo_Codigo;
	private javax.swing.JRadioButton btnGrupo_Descricao;
	private javax.swing.JRadioButton btnGrupo_Subgrupo_Codigo;
	private javax.swing.JRadioButton btnGrupo_Subgrupo_Descricao;
	private javax.swing.JRadioButton btnGrupo_Subgrupo_agru;
	private javax.swing.JRadioButton btnGrupo_agru;
	private javax.swing.JRadioButton btnImpressao_aut;
	private javax.swing.JButton btnImprimir;
	private javax.swing.JRadioButton btnNumeroItem;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JRadioButton btnSecao;
	private javax.swing.JRadioButton btnSemAgrupar_agru;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JLabel linha;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JRadioButton getBtnAmbiente_agru() {
		return btnAmbiente_agru;
	}

	public void setBtnAmbiente_agru(javax.swing.JRadioButton btnAmbiente_agru) {
		this.btnAmbiente_agru = btnAmbiente_agru;
	}

	public javax.swing.JButton getBtnCancelar() {
		return btnCancelar;
	}

	public void setBtnCancelar(javax.swing.JButton btnCancelar) {
		this.btnCancelar = btnCancelar;
	}

	public javax.swing.JRadioButton getBtnCodigoProduto() {
		return btnCodigoProduto;
	}

	public void setBtnCodigoProduto(javax.swing.JRadioButton btnCodigoProduto) {
		this.btnCodigoProduto = btnCodigoProduto;
	}

	public javax.swing.JRadioButton getBtnDescricao() {
		return btnDescricao;
	}

	public void setBtnDescricao(javax.swing.JRadioButton btnDescricao) {
		this.btnDescricao = btnDescricao;
	}

	public javax.swing.JRadioButton getBtnGrupo_Codigo() {
		return btnGrupo_Codigo;
	}

	public void setBtnGrupo_Codigo(javax.swing.JRadioButton btnGrupo_Codigo) {
		this.btnGrupo_Codigo = btnGrupo_Codigo;
	}

	public javax.swing.JRadioButton getBtnGrupo_Descricao() {
		return btnGrupo_Descricao;
	}

	public void setBtnGrupo_Descricao(javax.swing.JRadioButton btnGrupo_Descricao) {
		this.btnGrupo_Descricao = btnGrupo_Descricao;
	}

	public javax.swing.JRadioButton getBtnGrupo_Subgrupo_Codigo() {
		return btnGrupo_Subgrupo_Codigo;
	}

	public void setBtnGrupo_Subgrupo_Codigo(javax.swing.JRadioButton btnGrupo_Subgrupo_Codigo) {
		this.btnGrupo_Subgrupo_Codigo = btnGrupo_Subgrupo_Codigo;
	}

	public javax.swing.JRadioButton getBtnGrupo_Subgrupo_Descricao() {
		return btnGrupo_Subgrupo_Descricao;
	}

	public void setBtnGrupo_Subgrupo_Descricao(javax.swing.JRadioButton btnGrupo_Subgrupo_Descricao) {
		this.btnGrupo_Subgrupo_Descricao = btnGrupo_Subgrupo_Descricao;
	}

	public javax.swing.JRadioButton getBtnGrupo_Subgrupo_agru() {
		return btnGrupo_Subgrupo_agru;
	}

	public void setBtnGrupo_Subgrupo_agru(javax.swing.JRadioButton btnGrupo_Subgrupo_agru) {
		this.btnGrupo_Subgrupo_agru = btnGrupo_Subgrupo_agru;
	}

	public javax.swing.JRadioButton getBtnGrupo_agru() {
		return btnGrupo_agru;
	}

	public void setBtnGrupo_agru(javax.swing.JRadioButton btnGrupo_agru) {
		this.btnGrupo_agru = btnGrupo_agru;
	}

	public javax.swing.JRadioButton getBtnImpressao_aut() {
		return btnImpressao_aut;
	}

	public void setBtnImpressao_aut(javax.swing.JRadioButton btnImpressao_aut) {
		this.btnImpressao_aut = btnImpressao_aut;
	}

	public javax.swing.JButton getBtnImprimir() {
		return btnImprimir;
	}

	public void setBtnImprimir(javax.swing.JButton btnImprimir) {
		this.btnImprimir = btnImprimir;
	}

	public javax.swing.JRadioButton getBtnNumeroItem() {
		return btnNumeroItem;
	}

	public void setBtnNumeroItem(javax.swing.JRadioButton btnNumeroItem) {
		this.btnNumeroItem = btnNumeroItem;
	}

	public javax.swing.JButton getBtnSalvar() {
		return btnSalvar;
	}

	public void setBtnSalvar(javax.swing.JButton btnSalvar) {
		this.btnSalvar = btnSalvar;
	}

	public javax.swing.JRadioButton getBtnSecao() {
		return btnSecao;
	}

	public void setBtnSecao(javax.swing.JRadioButton btnSecao) {
		this.btnSecao = btnSecao;
	}

	public javax.swing.JRadioButton getBtnSemAgrupar_agru() {
		return btnSemAgrupar_agru;
	}

	public void setBtnSemAgrupar_agru(javax.swing.JRadioButton btnSemAgrupar_agru) {
		this.btnSemAgrupar_agru = btnSemAgrupar_agru;
	}

}
